name: CPack_action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Creating directory for future binary and source code
      run: |
        mkdir artifacts
    
    - name: Build a *solver* application
      run: |
        cmake -H. -B_build
        cmake --build _build --target package
        cd _build
        cpack -G "TGZ"
        cpack -G "DEB"
        cpack -G "RPM"
        cpack -G "ZIP"
        mv *.tar.gz ../../artifacts
        mv *.deb ../../artifacts
        mv *.rpm ../../artifacts
        mv *.zip ../../artifacts
      shell: bash
      working-directory: solver_application

    - name: Upload_artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: artifacts
