name: CPack_action
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Creating directory for future binary and source code
      run: |
        mkdir bin
    
    - name: Build a *formatter* library
      run: |
        cmake -H. -B_build
        cmake --build _build
      shell: bash
      working-directory: formatter_lib
      
    - name: Build a *formatter_ex* library
      run: |
        cmake -H. -B_build
        cmake --build _build
      shell: bash
      working-directory: formatter_ex_lib
      
    - name: Build a *solver* library
      run: |
        cmake -H. -B_build
        cmake --build _build
      shell: bash
      working-directory: solver_lib
      
    - name: Build a *solver* application
      run: |
        cmake -H. -B_build
        cmake --build _build
        cd _build
        mv solver_app ../../bin
      shell: bash
      working-directory: solver_application
